<?php
/**
 * @file
 * Implementation of default hooks for primo service integration.
 */

include_once 'primo_search.features.inc';
include_once 'primo_search.pages.inc';


/**
 * Implements hook_menu().
 */
function primo_search_menu() {
  $items['admin/config/primo'] = array(
    'title' => 'Primo',
    'description' => 'Use primo service',
    'weight' => 1,
    'position' => 'right',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access administration pages'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );
  $items['admin/config/primo/search'] = array(
    'title' => 'Primo search',
    'description' => 'Administration page for the primo search service integration',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('primo_search_admin_form'),
    'access arguments' => array('access administration pages'),
    'file' => 'primo_search.admin.inc',
    'file path' => drupal_get_path('module', 'primo_search'),
  );
  $items['primo/results/ajax'] = array(
    'title' => 'Primo carousel items',
    'description' => 'Ajax page for primo carousel items',
    'page callback' => 'primo_search_results_ajax',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function primo_search_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools' && $plugin_type == 'content_types') {
    return 'plugins/content_types';
  }
}

/**
 * Implements hook_theme().
 */
function primo_search_theme($existing, $type, $theme, $path) {
  return array(
    'primo_search_item' => array(
      'variables' => array(),
      'template' => 'primo-search-item',
      'path' => $path . '/templates',
    ),
    'primo_search_grid' => array(
      'variables' => array(),
      'template' => 'primo-search-grid',
      'path' => $path . '/templates',
    ),
    'primo_carousel_cover' => array(
      'variables' => array(),
      'template' => 'primo-carousel-cover',
      'path' => $path . '/templates',
    ),
    'primo_search_carousel' => array(
      'variables' => array(),
      'template' => 'primo-search-carousel',
      'path' => $path . '/templates',
    ),
    'primo_image' => array(
      'variables' => array(
        'style_name' => NULL,
        'path' => NULL,
        'alt' => NULL,
        'title' => NULL,
        'attributes' => array(),
        'remote' => NULL,
      ),
    ),
  );
}

/**
 * Theme image of the item based on the url and image style.
 *
 * @param $variables
 *   Default parameters for image theme: style name, image path.
 *
 * @return string
 *   Html code of the image.
 */
function theme_primo_image($variables) {
  $style_path = image_style_path($variables['style_name'], $variables['path']);
  if (!file_exists($style_path)) {
    $style = image_style_load($variables['style_name']);
    image_style_create_derivative($style, $variables['path'], $style_path);
  }
  $variables['path'] = $style_path;

  return theme('image', $variables);
}

function primo_search_results_ajax($index) {
  $options = array(
    array('index' => '0',   'title' =>  t('Recent books')),
    array('index' => '001', 'title' =>  t('Management')),
    array('index' => '002', 'title' =>  t('Jura')),
    array('index' => '003', 'title' =>  t('Politics')),
    array('index' => '004', 'title' =>  t('Economy')),
    array('index' => '005', 'title' =>  t('Organization and Leadership')),
    array('index' => '006', 'title' =>  t('Other Literature')),
  );

  if ($index == 0) {
    $subjects = array_map(function ($option) { return $option['index']; }, array_slice($options, 1));
    $subject_id = implode('+OR+', $subjects);
  }
  else {
    $subject_id = $options[$index]['index'];
  }

  $content = '';
  $items = primo_search_get_items_by_subject($subject_id);

  // If cache have been found theme search carousel pages.
  if (!empty($items)) {
    foreach ($items as $item) {
      $field = _primo_search_filter_fields($item['attributes']);

      // Skip items without image from the default category.
      if ((!isset($field['image']) || !$field['image']) && $index == 0) {
        continue;
      }

      $image_path = (isset($field['image']) && $field['image']) ? $field['image'] : drupal_get_path('module', 'primo_search') . '/img/default.png';
      $image = theme_primo_image(array('style_name' => 'primo_carousel_cover', 'path' => $image_path));
      $link = _primo_search_title_link($item['doc_number']);
      $content .= theme(
        'primo_carousel_cover',
        array(
          'image' => $image,
          'link' => $link,
          'title' => !empty($field['title']) ? $field['title'] : FALSE,
        )
      );
    }

  }

  // Return JSON output.
  drupal_json_output(array(
    'title' => $options[$index]['title'],
    'content' => $content,
    'index' => $index,
  ));
  drupal_exit();
}
